# Generated by Django 4.0.4 on 2022-04-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wash_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип мойки',
                'verbose_name_plural': 'Типы мойки',
            },
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_type', models.ForeignKey(blank=True, db_column='wash_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wash_type', verbose_name='Тип мойки')),
            ],
            options={
                'verbose_name': 'Бланк',
                'verbose_name_plural': 'Бланки',
            },
        ),
    ]
