# Generated by Django 4.0.4 on 2022-04-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blank_grz_blank_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wash_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man', models.CharField(blank=True, max_length=32, null=True, verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': 'Мойщик',
                'verbose_name_plural': 'Мойщики',
            },
        ),
        migrations.AddField(
            model_name='blank',
            name='car_mark',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='blank',
            name='wash_man',
            field=models.ForeignKey(blank=True, db_column='wash_man', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wash_man', verbose_name='Мойщик'),
        ),
    ]
