# Generated by Django 4.0.4 on 2022-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wash_man_blank_car_mark_blank_wash_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='price',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Цена'),
        ),
    ]
