# Generated by Django 4.0.3 on 2022-04-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blank_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_class', models.CharField(blank=True, max_length=1, null=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Класс авто',
                'verbose_name_plural': 'Классы авто',
            },
        ),
        migrations.AddField(
            model_name='blank',
            name='b_carpets',
            field=models.BooleanField(default=False, verbose_name='Коврики'),
        ),
        migrations.AddField(
            model_name='blank',
            name='b_cleaning',
            field=models.BooleanField(default=False, verbose_name='Химчистка'),
        ),
        migrations.AddField(
            model_name='blank',
            name='b_trunk',
            field=models.BooleanField(default=False, verbose_name='Багажник'),
        ),
        migrations.AddField(
            model_name='blank',
            name='notes',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='blank',
            name='car_class',
            field=models.ForeignKey(blank=True, db_column='car_class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car_class', verbose_name='Класс авто'),
        ),
    ]
