# Generated by Django 4.0.3 on 2022-05-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_class_blank_b_carpets_blank_b_cleaning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
            },
        ),
        migrations.AddField(
            model_name='blank',
            name='b_black',
            field=models.BooleanField(default=False, verbose_name='Чернение'),
        ),
        migrations.AddField(
            model_name='blank',
            name='b_degreasing',
            field=models.BooleanField(default=False, verbose_name='Обезжиривание'),
        ),
        migrations.AddField(
            model_name='blank',
            name='b_rain',
            field=models.BooleanField(default=False, verbose_name='Анти-дождь'),
        ),
        migrations.AddField(
            model_name='blank',
            name='b_tinting',
            field=models.BooleanField(default=False, verbose_name='Тонировка'),
        ),
        migrations.AddField(
            model_name='blank',
            name='b_window',
            field=models.BooleanField(default=False, verbose_name='Стёкла'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='b_cleaning',
            field=models.BooleanField(default=False, verbose_name='Пылесос'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='notes',
            field=models.TextField(blank=True, max_length=360, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='blank',
            name='date',
            field=models.ForeignKey(blank=True, db_column='date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.date', verbose_name='Дата'),
        ),
    ]
