# Generated by Django 4.0.3 on 2022-05-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_date_blank_b_black_blank_b_degreasing_blank_b_rain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.AddField(
            model_name='blank',
            name='sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='blank',
            name='pay_type',
            field=models.ForeignKey(blank=True, db_column='pay', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pay', verbose_name='Способ оплаты'),
        ),
    ]
