# Generated by Django 4.0.3 on 2022-05-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pay_blank_sale_blank_pay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryClining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairs', models.IntegerField(blank=True, null=True, verbose_name='Кресло')),
                ('b_full', models.BooleanField(default=False, verbose_name='Полная')),
                ('b_floor', models.BooleanField(default=False, verbose_name='Пол')),
                ('b_ceiling', models.BooleanField(default=False, verbose_name='Потолок')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.AddField(
            model_name='blank',
            name='dry_clining',
            field=models.ForeignKey(blank=True, db_column='dry_clining', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dryclining', verbose_name='Химчистка'),
        ),
    ]
