# Generated by Django 4.0.3 on 2022-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dryclining_blank_dry_clining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blank',
            name='dry_clining',
        ),
        migrations.AddField(
            model_name='blank',
            name='dry_clining',
            field=models.ManyToManyField(blank=True, db_column='dry_clining', null=True, to='core.dryclining', verbose_name='Химчистка'),
        ),
    ]
