# Generated by Django 4.0.3 on 2022-05-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_blank_dry_clining_blank_dry_clining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blank',
            name='dry_clining',
        ),
        migrations.AddField(
            model_name='blank',
            name='dry_clining',
            field=models.ForeignKey(blank=True, db_column='dry_clining', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dryclining', verbose_name='Химчистка'),
        ),
    ]
