# Generated by Django 4.0.3 on 2022-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_blank_dry_clining_blank_dry_clining'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='chairs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кресло'),
        ),
        migrations.AddField(
            model_name='blank',
            name='dc_ceiling',
            field=models.BooleanField(default=False, verbose_name='Потолок'),
        ),
        migrations.AddField(
            model_name='blank',
            name='dc_floor',
            field=models.BooleanField(default=False, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='blank',
            name='dc_full',
            field=models.BooleanField(default=False, verbose_name='Полная'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='dry_clining',
            field=models.BooleanField(default=False, verbose_name='Полная'),
        ),
        migrations.DeleteModel(
            name='DryClining',
        ),
    ]
